### ISSUE TITLE
Some bugs on mobile

### ISSUE THREAD

**Issue by Sissiogamer1** [ChristofferHolmesland/miniweb#3]
You cannot walk sideways but only above, below and oblique in any direction, but not to the right and to the left
You cannot walk and perform any action at the same time
If you hold down the action key it will execute it only once, while with the inventory key I think it is right that it is executed only 1 time if held down
Beside these problems, really good job on minicho! And thank you to please instantly any of our requests for the game

**Comment by ChristofferHolmesland** [comment]
>You cannot walk sideways but only above, below and oblique in any direction, but not to the right and to the left
>You cannot walk and perform any action at the same time

Fixed these.

Not sure if the player should be able to hold down the attack button yet.
